// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCb3_PTFAykI3Ghgvkljj7UOLUUANG7ZF0',
    appId: '1:742306487413:web:d49b06235ef443b870ac3c',
    messagingSenderId: '742306487413',
    projectId: 'star-wars-ea0de',
    authDomain: 'star-wars-ea0de.firebaseapp.com',
    storageBucket: 'star-wars-ea0de.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXoHZwaK1yR1PgevTKLpMAhzrOeqzG3H4',
    appId: '1:742306487413:android:fad5a1f226f108ac70ac3c',
    messagingSenderId: '742306487413',
    projectId: 'star-wars-ea0de',
    storageBucket: 'star-wars-ea0de.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2XV8WgH_2Cr0MCQCfKxcmfiRi7GPpVf4',
    appId: '1:742306487413:ios:2df050a493bd318670ac3c',
    messagingSenderId: '742306487413',
    projectId: 'star-wars-ea0de',
    storageBucket: 'star-wars-ea0de.appspot.com',
    iosBundleId: 'com.example.starWarsApp',
  );
}
